import { getStreamTimes } from "@/lib/stream-times";
import Head from "next/head";

interface props {
  props: {};
}

export function getStaticProps(): props {
  const streamTimes = getStreamTimes();
  return {
    props: {
      streamTimes,
    },
  };
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Stream Timer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="text-3xl text-center font-bold underline ">
          Hello world
        </div>
      </main>
    </>
  );
}
